image: docker:latest

services:
  - docker:dind

stages:
  - build_push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin

build_push:
  stage: build_push
  script:
    - docker build -t $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA
  only:
    - main
