image: docker:latest

services:
  - docker:dind

variables:
  GIT_CONFIG_PARAMETERS: "'http.version=HTTP/1.1' 'http.postBuffer=524288000'"
  GIT_DEPTH: "1"

stages:
  - test
  - build_push

trivy_scan:
  stage: test
  image: alpine:3.18  # No need for Docker image here!
  variables:
    TRIVY_CACHE_DIR: ".trivycache/"
  before_script:
    - apk add --no-cache wget tar
    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name"\:' | sed -E 's/.*"v([^"]+)".*/\1/')
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
  script:
    # Scan the source code and Dockerfile directly (Faster, no build needed)
    - ./trivy fs --exit-code 0 --format template --template "@./contrib/gitlab.tpl" -o gl-container-scanning-report.json .
    - ./trivy fs --exit-code 0 --severity HIGH .
    - ./trivy fs --exit-code 1 --severity CRITICAL .
    - ./trivy fs --scanners secret --exit-code 0 .
  cache:
    paths:
      - ".trivycache/"
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json

build_push:
  stage: build_push
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --no-cache -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
