image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build_push

trivy:
  stage: test
  image: docker:stable
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE: $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHA
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  before_script:
    - export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name"\:' | sed -E 's/.*"v([^"]+)".*/\1/')
    - echo $TRIVY_VERSION
    - wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
  allow_failure: true
  script:
    # Build the Docker image for scanning
    - docker build -t $IMAGE .
    # Generate a container scanning report in GitLab's required format
    - ./trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json $IMAGE
    # Print summary report for high severity issues
    - ./trivy image --exit-code 0 --severity HIGH $IMAGE
    # Fail if any CRITICAL vulnerabilities are found
    - ./trivy image --exit-code 1 --severity CRITICAL $IMAGE
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json

build_push:
  stage: build_push
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA $DOCKER_USER/devops-maturity-model:latest
    - docker push $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USER/devops-maturity-model:latest
  only:
    - main
