image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build_push

trivy:
  stage: test
  image: docker:stable
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE: $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHA
    TRIVY_NO_PROGRESS: "true"
    TRIVY_CACHE_DIR: ".trivycache/"
  before_script:
    - chmod +x trivy_setup.sh
    - ./trivy_setup.sh
  allow_failure: true
  script:
    - docker build -t $IMAGE .
    - ./trivy image --exit-code 0 --format template --template "@/contrib/gitlab.tpl" -o gl-container-scanning-report.json $IMAGE
    - ./trivy image --exit-code 0 --severity HIGH $IMAGE
    - ./trivy image --exit-code 1 --severity CRITICAL $IMAGE
  cache:
    paths:
      - .trivycache/
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json

build_push:
  stage: build_push
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA .
    - docker tag $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA $DOCKER_USER/devops-maturity-model:latest
    - docker push $DOCKER_USER/devops-maturity-model:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USER/devops-maturity-model:latest
  only:
    - main
